Loading model 'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B'... (This may take a while for large models)
INFO 03-02 16:26:54 __init__.py:207] Automatically detected platform cuda.
ERROR 03-02 16:26:55 config.py:102] Error retrieving file list: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B/tree/main?recursive=True&expand=False (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14da8f099f10>: Failed to establish a new connection: [Errno 111] Connection refused'))"), '(Request ID: 062beead-8b89-4c6e-aec0-d80a42935fde)'), retrying 1 of 2
ERROR 03-02 16:26:57 config.py:100] Error retrieving file list: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B/tree/main?recursive=True&expand=False (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14da8f099490>: Failed to establish a new connection: [Errno 111] Connection refused'))"), '(Request ID: e84a9479-412a-4876-87a6-5c91a542943c)')
